version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16.13.0
    working_directory: ~/repo
    steps:
      # Checkout will check the code from github
      - checkout
      # Install packages
      - run: npm install
      - run: npm test
